config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'toppages/about', to: 'toppages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update]
  
  resources :items do
    resources :comments, only: [:create, :destroy]
  end
  
  # メッセージ
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :destroy]
  # 通知
  resources :notifications, only: [:index, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :visitor, class_name: "User", optional: true
  belongs_to :visited, class_name: "User", optional: true
  belongs_to :item, optional: true
  belongs_to :comment, optional: true
  belongs_to :room, optional: true
  belongs_to :message, optional: true
  validates :visitor_id, presence: true
  validates :visited_id, presence: true
  ACTION_VALUES = ["comment", "message"]
  validates :action,  presence: true, inclusion: {in:ACTION_VALUES}
  validates :checked, inclusion: {in: [true,false]}
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications
    #通知画面を開くとcheckedをtrueにして通知確認済にする
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
  
  def destroy
      @notifications =current_user.passive_notifications.destroy_all
      redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    #通知を送ってきたユーザーを取得
    @visitor = notification.visitor
    #コメントの内容を通知に表示する
    @comment = nil
    @visitor_comment = notification.comment_id
    #メッセージの内容を通知に表示する
    @message = nil
    @visitor_message = notification.message_id
    # notification.actionがfollowかfavoriteかcommentかで処理を変える
    case notification.action
    when 'comment' then
      #コメントの内容と投稿のタイトルを取得　      
      @comment = Comment.find_by(id: @visitor_comment)
      @comment_content = @comment.content
      @item_name = @comment.item.name
      tag.a(@visitor.name, href: user_path(@visitor)) + 'が' + tag.a("#{@item_name}", href: item_path(notification.item_id)) + 'にコメントしました'

    when 'message' then
      #DMの内容と投稿のDMの相手を取得　      
      @message = Message.find_by(id: @visitor_message)
      @message_content = @message.content
      # @message_title = @comment.room.name
      tag.a(@visitor.name, href: user_path(@visitor)) + 'から' + tag.a("DM", href: room_path(notification.room_id)) + 'が来ました'
    end
    
  end
  
  # 通知の知らせ
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<div class="notification-view">
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
  <br>
  <!--<%# if !@comment.nil? %>-->
  <!--  <p class="notification-comment"><%#= @comment %></p>-->
  <!--<%# end %>-->
  
  <!--<%# if !@message.nil? %>-->
  <!--  <p class="notification-message"><%#= @message %></p>-->
  <!--<%# end %>-->
</div>

app/views/notifications/index.html.erb
<h3 class="text-center">通知</h3>
<%= link_to "通知削除", notification_path(@notifications), method: :delete ,class: "fas fa-trash" %>
<% if @notifications.exists? %>
  <div class="notification-index">
    <%= render @notifications %>
  </div>
<% else %>
  <p>通知はありません</p>
<% end %>