config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'toppages/about', to: 'toppages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update]
  
  resources :items do
    resources :comments, only: [:create, :destroy]
  end
  
  # メッセージ
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :destroy]
  # 通知
  resources :notifications, only: [:index, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  # 画像アップロード
  mount_uploader :image, ImageUploader
  #アイテムとの１対多
  has_many :items, dependent: :destroy
  #コメント機能
  has_many :comments, dependent: :destroy
  # ダイレクトメッセージ機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  # 通知
  has_many :active_notifications, foreign_key:"visitor_id", class_name: "Notification", dependent: :destroy
  has_many :passive_notifications, foreign_key:"visited_id", class_name: "Notification", dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  
  def show
    #メッセージ
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = '更新しました'
      redirect_to @user
    else
      flash.now[:danger] = "更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :introduction)
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_url
    end
  end
  
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="main">
  <div class="container">
    <div class="text-center">
      <h3><span class="text-danger">D</span>ansha<span class="text-danger">L</span>ist</h3>
    </div>
    <div class="row">
      <div class="col-sm-8 offset-sm-2 border  mt-4 mb-4">
        <!--フォーム-->
        <%= form_with(model: @user, local: true) do |f| %>
          <!--画像表示-->
          <div class="text-center pb-0 relative">
            <div class="user_img_wrap rounded-circle" id="image">
              <% if @user.image? %>
                <%= image_tag @user.image.to_s, :size => '200x200', :class => 'rounded-circle user-image', :alt => 'ユーザーアイコン' %>
              <% else %>
                <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592050958/default_fyleea.jpg", :size => '200x200', :class => 'rounded-circle user-image', :alt => 'ユーザーアイコン' %>
              <% end %>
              <i class="fas fa-camera" style="font-size: 60px; top: 40%; left: 46%;"></i>
            </div>
          </div>
          <%= f.file_field :image %>
          
          
          <%= render 'layouts/error_messages', model: f.object %>
          
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :introduction, '自己紹介' %>
            <%= f.text_area :introduction, class: 'form-control', rows: 5 %>
          </div>
          <%= f.submit '更新', class: 'btn btn-danger btn-block mb-4' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main">
  <div class="container">
    <div class="text-center">
      <h3><span class="text-danger">D</span>ansha<span class="text-danger">L</span>ist</h3>
    </div>
    <div class="row">
      <div class="col-sm-8 offset-sm-2 border  mt-4 mb-4">
        <div class="text-center">
          <h3>会員登録</h3>
        </div>
        <div class="row mb-4">
          <div class="col-md-6 offset-md-3">
            <%= form_with(model: @user, local: true) do |f| %>
              <%= render 'layouts/error_messages', model: f.object %>
              <div class="form-group">
                <%= f.label :name, 'お名前' %><span class="text-danger">　※</span>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email, 'メールアドレス' %><span class="text-danger">　※</span>
                <%= f.email_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password, 'パスワード（6字以上）' %><span class="text-danger">※</span>
                <%= f.password_field :password, class: 'form-control' %>
               </div>
              <div class="form-group">
                 <%= f.label :password_confirmation, 'パスワード（確認）' %><span class="text-danger">※</span>
                 <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
              <div class="text-right">
                <%= f.submit '   登録   ', class: 'btn btn-danger' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 border mt-4 mb-4">
        <!--画像-->
        <div class="text-center pb-0 mb-1">
          <% if @user.image? %>
            <%= image_tag @user.image.to_s, :size => '200x200', :class => 'rounded-circle', :alt => 'ユーザーアイコン' %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592050958/default_fyleea.jpg", :size => '200x200', :class => 'rounded-circle', :alt => 'ユーザーアイコン' %>
          <% end %>
        </div>
        <!--編集機能-->
        <div class="text-center">
          <%= @user.name %>
          <% if current_user == @user %>
            <%= link_to '(編集)', edit_user_path(@user) %>
            <!--通知-->
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle" style="color: gold;"></i>
            <% end %>
            <%= link_to '通知', notifications_path(current_user) %>
            <% end %>
        </div>
        
        
        
        <!--自己紹介-->
        <div class="card">
          <p class="mb-0 text-center pt-0 pb-0">自己紹介</p>
          <div class="card-body">
            <%= @user.introduction %>
            <%#= simple_format @user.introduction %>
          </div>
        </div>
        
        
        
        <!--ダイレクトメッセージ-->
        <div class="text-center">
          <% unless @user.id == current_user.id %>
            <% if @isRoom == true %>
              <!--<p class="btn btn-secondary">-->
              <a href="/rooms/<%= @roomId %>" >ダイレクトメッセージ</a>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @entry do |e| %>
                  <%= e.hidden_field :user_id, :value=> @user.id %>
                <% end %>
                <%= f.submit "DMを始める", class: 'btn btn-secondary' %>
              <%end %>
            <% end %>
          <% end %>
        </div>
        
        
        
        
        
        
        <!--アイテム一覧-->
        <div class="text-center pb-1">
          <h5>アイテム数 <%= @user.items.count%></h5>
        </div>
        <div class="row">
          <% @user.items.each do |item| %>
          
            
            <div class="col-md-4 text-center mb-5">
            <div class="card">
              <div class="card-body c-b-bg">
                <div class="card-title">
                  <%= link_to item.name, item , class: 'text-light'%>
                </div>
              </div>
              <div class="card-img-top">
                <%if item.image?%>
                  <%= image_tag item.image.to_s, :size => '100x150', :alt => 'アイテム画像' %>
                <% else %>
                  <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592051211/m_e_others_500_dr00a1.png", :size => '100x150',:alt => 'アイテム画像' %>
                <% end %>
              </div>
              
            </div>  
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>