config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'toppages/about', to: 'toppages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update]
  
  resources :items do
    resources :comments, only: [:create, :destroy]
  end
  
  # メッセージ
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :destroy]
  # 通知
  resources :notifications, only: [:index, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 40 }
  validates :introduction,length: { maximum: 200 }
  
  # 画像アップロード
  mount_uploader :image, ImageUploader
  #コメント機能
  has_many :comments, dependent: :destroy
  # 通知
  has_many :notifications, dependent: :destroy
  
  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    #同じ投稿にコメントしているユーザーに通知を送る。（current_userと投稿ユーザーのぞく）
    temp_ids = Comment.where(item_id: id).where.not("user_id=? or user_id=?", current_user.id,user_id).select(:user_id).distinct
    #取得したユーザー達へ通知を作成。（user_idのみ繰り返し取得）
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    #投稿者へ通知を作成
    save_notification_comment!(current_user, comment_id, user_id)
  end
  
  def save_notification_comment!(current_user, comment_id, visited_id)
      notification = current_user.active_notifications.new(
        item_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: 'comment'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in, except: [:index]
  before_action :correct_user, only: [:destroy, :edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @search = Item.ransack(params[:q])
    @items = @search.result.order(updated_at: :desc).page(params[:page]).per(18)
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = 'アイテムを追加しました'
      redirect_to root_url
    else
      @items = current_user.items.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'アイテムの追加に失敗しました。'
      render :new
    end
  end
  
  def show
    @comments = @item.comments
    @comment = @item.comments.build
  end
  
  def edit
  end
  
  def update
    if @item.update(item_params)
      flash[:success] = 'アイテムが正常に更新されました'
      redirect_to @item
    else
      flash.now[:danger] = 'アイテムは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @item.destroy
    flash[:success] = 'アイテムを削除しました'
    redirect_to root_url
  end

  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :image)
  end
  
  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    unless @item || current_user.admin?
      redirect_to root_url
    end
  end
  
  def set_item
    @item = Item.find(params[:id]) 
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_items.html.erb
<% items.each do |item| %>
  <div class="col-md-4 text-center mt-0 mb-0">
    <div class="card">
      <div class="card-body c-b-bg">
        <div class="card-title">
          <%= link_to item.name, item , class: 'text-light'%>
        </div>
      </div>
      <div class="card-img-top">
        <%if item.image?%>
          <%= image_tag item.image.to_s, :size => '200x250', :alt => 'アイテム画像'%>
        <% else %>
          <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592051211/m_e_others_500_dr00a1.png", :size => '200x250', :class => "border", :alt => 'アイテム画像' %>
        <% end %>
      </div>
      
    </div>  
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="main">
  <div class="container">
    <div class="text-center">
      <h3><span class="text-danger">D</span>ansha<span class="text-danger">L</span>ist</h3>
    </div>
    <div class="row">
      <div class="col-sm-8 offset-sm-2 border  mt-4 mb-4">
        <div class="text-center pb-2">
          <h2>アイテム情報を編集</h2>
        </div>
        <div class="border mb-4"></div>
          
        <%= form_with(model: @item, local: true) do |f| %>
          <div class="text-center pt-0 pb-0 relative">
            <div class="img_wrap" id="image">
              <%if @item.image?%>
                <%= image_tag @item.image.to_s, :size => '200x250', :alt => "アイテム画像", :class => "border item-image" %>
                
              <% else %>
                <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592051211/m_e_others_500_dr00a1.png", :size => '200x250', :class => "border item-image", :alt => "アイテム画像" %>
                
              <% end %>
              <i class="fas fa-camera" style="font-size: 60px;"></i>
            </div>
          </div>
          <%= f.file_field :image %>
          
          <%= render 'layouts/error_messages', model: f.object %>
          
          
          
          
          <div class="form-group">
            <%= f.label :name, 'アイテム名' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :introduction, 'アイテム紹介' %>
            <%= f.text_area :introduction, class: 'form-control', rows: 5 %>
          </div>
          <%= f.submit '編集', class: 'btn btn-danger btn-block mb-4' %>
        <% end %>
        <div class="text-center pt-0">
          <%= link_to '戻る', @item %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="main-container">
  <div class="text-center">
    <h3>モノと人との出会い</h3>
    <h2><span class="text-danger">D</span>ansha<span class="text-danger">L</span>ist</h2>
  </div>
</div>
<div class="text-center">
  <h5>使わなくなった大切なモノを<br>誰かに使ってもらいたくありませんか？</h5>
</div>
<div class="main">
  <div class="container">
    
    <div class="row">
      <%= render 'items/items', items: @items%>
    </div>
    <div class="pull-right">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="main">
  <div class="container">
    <div class="text-center">
      <h3><span class="text-danger">D</span>ansha<span class="text-danger">L</span>ist</h3>
    </div>
    <div class="row">
      <div class="col-sm-8 offset-sm-2 border  mt-4 mb-4">
        <%= form_with(model: @item, local: true) do |f| %>
        <div class="text-center pb-2">
          <h2>アイテムを追加</h2>
        </div>
        <div class="border mb-4"></div>
        <!--画像新-->
        <div class="text-center pt-0 pb-0 relative">
          <div class="img_wrap" id="image">
            <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592051211/m_e_others_500_dr00a1.png", :size => '200x250', :class => "border item-image", :alt => "アイテム画像" %>
            <i class="fas fa-camera" style="font-size: 60px;"></i>
          </div>
        </div>
        <%= f.file_field :image %>
          <%= render 'layouts/error_messages', model: f.object %>
          
          <!--画像-->
          <!--<div class="form-group text-center">-->
          <!--  <%#= f.label :image,"画像" %>-->
          <!--  <%#= f.file_field :image %>-->
          <!--</div>-->
          
          
          <div class="form-group">
            <%= f.label :name, 'アイテム名' %>
            <%= f.text_field :name, class: 'form-control'%>
          </div>
          <div class="form-group">
            <%= f.label :introduction, 'アイテム紹介' %>
            <%= f.text_area :introduction, class: 'form-control', rows: 5 %>
          </div>
          <%= f.submit '追加', class: 'btn btn-danger btn-block mb-4' %>
        <% end %>
        <div class="text-center pt-0">
          <%= link_to '戻る', root_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2 border mt-4 mb-4">
        <div class="text-center">
          <h2><%= @item.name %></h2>
        </div>
        
        <div class="text-center pt-0 ">
          <%if @item.image?%>
            <%= image_tag @item.image.to_s, size: '200x250', alt: 'アイテム画像' %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592051211/m_e_others_500_dr00a1.png", size: '200x250', class: "border", alt: 'アイテム画像' %>
          <% end %>
        </div>
        
        <div class="pt-0 pb-0">
          <table>
            <tr>
              <th>ユーザー名</th>
              <td><%= link_to @item.user.name, @item.user %></td>
            </tr>
            <tr>
              <th>アイテムの説明</th>
              <!--<td><%#= @item.introduction%></td>-->
              <td><%= @item.introduction %></td>
              
            </tr>
            <tr>
              <th>🕔</th>
              <td><%= time_ago_in_words(@item.updated_at)%>前</td>
            </tr>
          </table>
        </div>
        <div class="mt-4">
          <% if current_user == @item.user  %>
            <%= link_to '編集', edit_item_path(@item), class: 'btn btn-danger btn-block mb-4' %>
          <% end %>
          <% if current_user == @item.user || current_user.admin? %>
            <%= link_to 'このアイテムを削除する', @item, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class:"btn btn-secondary btn-block mb-4" %>
          <% end %>
        </div>
        <div class="text-center">
          <%= link_to '戻る', root_path%>
        </div>
        
        <div class="comment-wrapper border-top">
          <div class="text-center">
            <h4 class="mt-4">コメント一覧</h4>
          </div>
          <% @comments.each do |c| %>
            <div>
              <% unless c.user.blank? %>
                <%if c.user.image?%>
                  <a href="<%= user_path(c.user_id) %>"><%= image_tag c.user.image.to_s,class:"rounded-circle icon_image mr-3 mb-3",size: '50x50', alt: 'アイコン画像'%></a>
                <% else %>
                  <a href="<%= user_path(c.user_id) %>"><%= image_tag "https://res.cloudinary.com/hqf8k8ltl/image/upload/v1592050958/default_fyleea.jpg",class:"rounded-circle icon_image mr-3 mb-3",size: '50x50', alt: 'アイコン画像'%></a>
                <% end %>
                <%= link_to c.user.name, user_path(c.user) %>
                <p><%= c.content %></p>
                🕔<%= time_ago_in_words(c.created_at)%>前
                <!--コメント削除-->
                <% if current_user == c.user || current_user == @item.user %>
                  <%= link_to 'コメントを削除する', item_comment_path(c.item.id ,c.id), method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
                <% end %>
                
                
                <% if current_user == @item.user && current_user != c.user %>
                  <div class="text-right">
                    <%= link_to "この方にDMを送る", user_path(c.user) %>
                  </div>
                <% end %>
              <% end %>
              
              
              
              
              <hr>
              
            </div>
            <!--<br />-->
          <% end %>
          <%# if user_signed_in? %>
            <%= form_with(model: [@item, @comment], local: true) do |f| %>
              <%= f.text_area :content, class: "form-control", rows: 5 %>
              <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
                <i class="far fa-comments"></i> 
                コメントする
              <% end %>
            <% end %>
          <%# end %>
        </div>
        
      </div>
    </div>
  </div>
</div>