config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'toppages/about', to: 'toppages#about'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update]
  
  resources :items do
    resources :comments, only: [:create, :destroy]
  end
  
  # メッセージ
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :destroy]
  # 通知
  resources :notifications, only: [:index, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> mb-0"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-light ml-5 mr-5">
    <a class="navbar-brand" href="/"><span class="text-danger">D</span>ansha<span class="text-danger">L</span>ist</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    
          
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to 'DanshaListについて', toppages_about_path, class: 'nav-link' %></li>
        <% if logged_in? %>
          
          
          
          <li class="nav-item"><%= link_to '追加', new_item_path, class: 'nav-link' %></li>
          <li class="nav-item"><% if unchecked_notifications.any? %>
                      <i class="fa fa-circle" style="color: gold;"></i>
                    <% end %><%= link_to 'マイページ', user_path(current_user) , class: 'nav-link'%></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete , class: 'nav-link'%></li>
        <% else %>
          <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <!--検索-->
    <div class="ml-5 mr-5 pl-4 pr-4 mb-2 text-right search_box">
      <%= search_form_for @search, url: items_path do |f| %>
        <%= f.search_field :name_cont, :placeholder => 'お探しのアイテムを入力してください', :style => "width: 70%; border: .1px solid;"  %>
        <%= button_tag sanitize('<i class="fa fa-search"></i>検索'), :type => "submit",
        :class =>"btn btn-default btn-s-md  pt-1 pl-0" %>
      <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DanshaList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <!--<div class="container">-->
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    <!--</div>-->
    <footer><p class="text-center pt-1 pb-1">©DanshaList2020</p></footer>
  </body>
</html>